# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2021.

version: "2"
services:
  serve:
    image: node:14-alpine
    container_name: serve
    working_dir: /app
    command: sh -c "npm i && npm run serve"
    volumes:
      - .:/app
    ports:
      - "8200:8200"
      - "35729:35729"

  build:
    image: node:14-alpine
    container_name: build
    working_dir: /app
    command: sh -c "npm i && npm run build"
    volumes:
      - .:/app
